### ISSUE TITLE
Gallery Submission Feedback

### ISSUE THREAD

**Issue by fa653** [webminds-inc/consent#1]
While reviewing your template, we noticed the following:

- [Required]: Incorrect format for template display name. Please format your template's display name to have the following format: "<company name> <template name>". Here is our template style guide for reference: https://developers.google.com/tag-platform/tag-manager/templates/style#name 
- [Recommended]: when using setDefaultConsentState in your template, it is recommended (but not required) to scope the request per region. API doc: https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate

**Comment by copthuy** [comment]
> While reviewing your template, we noticed the following:
> 
> * [Required]: Incorrect format for template display name. Please format your template's display name to have the following format: " ". Here is our template style guide for reference: https://developers.google.com/tag-platform/tag-manager/templates/style#name
> * [Recommended]: when using setDefaultConsentState in your template, it is recommended (but not required) to scope the request per region. API doc: https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate

I've updated the template display name and added region scope to the default state. Please review it again. Thanks

**Comment by philpott** [comment]
To make the template changes live you need to update your metadata.yaml file to point to the latest commit with the template changes.
